"""schema inicial completo (fase 0)

Revision ID: 422451fbb18f
Revises: 
Create Date: 2026-06-30 08:45:28.335984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '422451fbb18f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('pluggy_id', sa.String(length=16), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('description_translated', sa.String(length=255), nullable=True),
    sa.Column('parent_id', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categoria.pluggy_id'], name=op.f('fk_categoria_parent_id_categoria'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('pluggy_id', name=op.f('pk_categoria'))
    )
    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categoria_parent_id'), ['parent_id'], unique=False)

    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=True),
    sa.Column('totp_secret_cifrado', sa.Text(), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('salario_mensal_centavos', sa.BigInteger(), nullable=True),
    sa.Column('formacao', sa.String(length=255), nullable=True),
    sa.Column('ocupacao', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuario')),
    sa.UniqueConstraint('email', name=op.f('uq_usuario_email'))
    )
    op.create_table('config_telegram',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.String(length=64), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('notif_nova_transacao', sa.Boolean(), nullable=False),
    sa.Column('notif_nao_revisadas', sa.Boolean(), nullable=False),
    sa.Column('horario_1', sa.Time(), nullable=True),
    sa.Column('horario_2', sa.Time(), nullable=True),
    sa.Column('resumo_diario', sa.Boolean(), nullable=False),
    sa.Column('resumo_semanal', sa.Boolean(), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_config_telegram_usuario_id_usuario'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_config_telegram')),
    sa.UniqueConstraint('usuario_id', name=op.f('uq_config_telegram_usuario_id'))
    )
    with op.batch_alter_table('config_telegram', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_config_telegram_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('credencial_pluggy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id_cifrado', sa.Text(), nullable=False),
    sa.Column('client_secret_cifrado', sa.Text(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_credencial_pluggy_usuario_id_usuario'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credencial_pluggy')),
    sa.UniqueConstraint('usuario_id', name=op.f('uq_credencial_pluggy_usuario_id'))
    )
    with op.batch_alter_table('credencial_pluggy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credencial_pluggy_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('divisao_despesa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criado_por_usuario_id', sa.Integer(), nullable=False),
    sa.Column('outro_usuario_id', sa.Integer(), nullable=False),
    sa.Column('valor_centavos', sa.BigInteger(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('categoria_id', sa.String(length=16), nullable=True),
    sa.Column('modo_divisao', sa.String(length=24), nullable=False),
    sa.Column('quitada', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("modo_divisao IN ('pago_mim_dividir', 'pago_mim_recebo', 'pago_outro_dividir', 'pago_outro_recebo')", name=op.f('ck_divisao_despesa_modo_divisao')),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.pluggy_id'], name=op.f('fk_divisao_despesa_categoria_id_categoria'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['criado_por_usuario_id'], ['usuario.id'], name=op.f('fk_divisao_despesa_criado_por_usuario_id_usuario'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['outro_usuario_id'], ['usuario.id'], name=op.f('fk_divisao_despesa_outro_usuario_id_usuario'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_divisao_despesa'))
    )
    with op.batch_alter_table('divisao_despesa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_divisao_despesa_categoria_id'), ['categoria_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_divisao_despesa_criado_por_usuario_id'), ['criado_por_usuario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_divisao_despesa_outro_usuario_id'), ['outro_usuario_id'], unique=False)

    op.create_table('fonte_de_renda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=16), nullable=False),
    sa.Column('valor_estimado_centavos', sa.BigInteger(), nullable=False),
    sa.Column('recorrencia', sa.String(length=16), nullable=False),
    sa.Column('fonte', sa.String(length=255), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("recorrencia IN ('mensal', 'trimestral', 'semestral', 'anual', 'irregular')", name=op.f('ck_fonte_de_renda_recorrencia')),
    sa.CheckConstraint("tipo IN ('fixa', 'variavel')", name=op.f('ck_fonte_de_renda_tipo')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_fonte_de_renda_usuario_id_usuario'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fonte_de_renda'))
    )
    with op.batch_alter_table('fonte_de_renda', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fonte_de_renda_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('instituicao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('pluggy_connector_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_instituicao_usuario_id_usuario'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instituicao'))
    )
    with op.batch_alter_table('instituicao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instituicao_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('objetivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('justificativa', sa.Text(), nullable=True),
    sa.Column('valor_alvo_centavos', sa.BigInteger(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_objetivo_usuario_id_usuario'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_objetivo'))
    )
    with op.batch_alter_table('objetivo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_objetivo_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('orcamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.String(length=16), nullable=False),
    sa.Column('limite_padrao_centavos', sa.BigInteger(), nullable=False),
    sa.Column('recorrente', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.pluggy_id'], name=op.f('fk_orcamento_categoria_id_categoria'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_orcamento_usuario_id_usuario'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orcamento')),
    sa.UniqueConstraint('usuario_id', 'categoria_id', name=op.f('uq_orcamento_usuario_id'))
    )
    with op.batch_alter_table('orcamento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orcamento_categoria_id'), ['categoria_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orcamento_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('sessao',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revogada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_sessao_usuario_id_usuario'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessao'))
    )
    with op.batch_alter_table('sessao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessao_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('item_pluggy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credencial_id', sa.Integer(), nullable=False),
    sa.Column('pluggy_item_id', sa.Text(), nullable=False),
    sa.Column('connector_id', sa.Integer(), nullable=True),
    sa.Column('connector_nome', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('status_detalhe', sa.String(length=255), nullable=True),
    sa.Column('ultimo_sync_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['credencial_id'], ['credencial_pluggy.id'], name=op.f('fk_item_pluggy_credencial_id_credencial_pluggy'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_item_pluggy_usuario_id_usuario'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item_pluggy'))
    )
    with op.batch_alter_table('item_pluggy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_pluggy_credencial_id'), ['credencial_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_pluggy_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('orcamento_mensal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orcamento_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.String(length=16), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('limite_centavos', sa.BigInteger(), nullable=False),
    sa.Column('editado_manualmente', sa.Boolean(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.pluggy_id'], name=op.f('fk_orcamento_mensal_categoria_id_categoria'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamento.id'], name=op.f('fk_orcamento_mensal_orcamento_id_orcamento'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_orcamento_mensal_usuario_id_usuario'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orcamento_mensal')),
    sa.UniqueConstraint('usuario_id', 'categoria_id', 'ano', 'mes', name=op.f('uq_orcamento_mensal_usuario_id'))
    )
    with op.batch_alter_table('orcamento_mensal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orcamento_mensal_categoria_id'), ['categoria_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orcamento_mensal_orcamento_id'), ['orcamento_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orcamento_mensal_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('conta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('instituicao_id', sa.Integer(), nullable=False),
    sa.Column('pluggy_account_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('subtype', sa.String(length=32), nullable=True),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('marketing_name', sa.String(length=255), nullable=True),
    sa.Column('numero', sa.String(length=64), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('tax_number', sa.String(length=32), nullable=True),
    sa.Column('saldo_centavos', sa.BigInteger(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('objetivo_id', sa.Integer(), nullable=True),
    sa.Column('pluggy_criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pluggy_atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("subtype IN ('CHECKING_ACCOUNT', 'SAVINGS_ACCOUNT', 'CREDIT_CARD')", name=op.f('ck_conta_subtype')),
    sa.CheckConstraint("type IN ('BANK', 'CREDIT')", name=op.f('ck_conta_type')),
    sa.ForeignKeyConstraint(['instituicao_id'], ['instituicao.id'], name=op.f('fk_conta_instituicao_id_instituicao'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_id'], ['item_pluggy.id'], name=op.f('fk_conta_item_id_item_pluggy'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['objetivo_id'], ['objetivo.id'], name=op.f('fk_conta_objetivo_id_objetivo'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_conta_usuario_id_usuario'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conta')),
    sa.UniqueConstraint('pluggy_account_id', name=op.f('uq_conta_pluggy_account_id'))
    )
    with op.batch_alter_table('conta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conta_instituicao_id'), ['instituicao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conta_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conta_objetivo_id'), ['objetivo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conta_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('investimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('objetivo_id', sa.Integer(), nullable=True),
    sa.Column('pluggy_investment_id', sa.String(length=64), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('numero', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('subtype', sa.String(length=32), nullable=True),
    sa.Column('saldo_centavos', sa.BigInteger(), nullable=False),
    sa.Column('amount_centavos', sa.BigInteger(), nullable=True),
    sa.Column('amount_original_centavos', sa.BigInteger(), nullable=True),
    sa.Column('taxes_centavos', sa.BigInteger(), nullable=True),
    sa.Column('taxes2_centavos', sa.BigInteger(), nullable=True),
    sa.Column('amount_profit_centavos', sa.BigInteger(), nullable=True),
    sa.Column('amount_withdrawal_centavos', sa.BigInteger(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('value_unitario', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('isin', sa.String(length=20), nullable=True),
    sa.Column('issuer', sa.String(length=255), nullable=True),
    sa.Column('issuer_cnpj', sa.String(length=20), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('issue_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purchase_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('grace_period_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rate', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('rate_type', sa.String(length=32), nullable=True),
    sa.Column('rate_periodicity', sa.String(length=32), nullable=True),
    sa.Column('fixed_annual_rate', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('annual_rate', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('last_month_rate', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('last_twelve_months_rate', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('tax_exempt', sa.Boolean(), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('instituicao_emissora_nome', sa.String(length=255), nullable=True),
    sa.Column('instituicao_emissora_numero', sa.String(length=64), nullable=True),
    sa.Column('pluggy_criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pluggy_atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item_pluggy.id'], name=op.f('fk_investimento_item_id_item_pluggy'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['objetivo_id'], ['objetivo.id'], name=op.f('fk_investimento_objetivo_id_objetivo'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_investimento_usuario_id_usuario'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investimento')),
    sa.UniqueConstraint('pluggy_investment_id', name=op.f('uq_investimento_pluggy_investment_id'))
    )
    with op.batch_alter_table('investimento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investimento_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_investimento_objetivo_id'), ['objetivo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_investimento_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('assinatura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('valor_centavos', sa.BigInteger(), nullable=False),
    sa.Column('categoria_id', sa.String(length=16), nullable=True),
    sa.Column('periodicidade', sa.String(length=16), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('detectada_automaticamente', sa.Boolean(), nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("periodicidade IN ('mensal', 'trimestral', 'semestral', 'anual', 'irregular')", name=op.f('ck_assinatura_periodicidade')),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.pluggy_id'], name=op.f('fk_assinatura_categoria_id_categoria'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conta_id'], ['conta.id'], name=op.f('fk_assinatura_conta_id_conta'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_assinatura_usuario_id_usuario'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assinatura'))
    )
    with op.batch_alter_table('assinatura', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assinatura_categoria_id'), ['categoria_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assinatura_conta_id'), ['conta_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assinatura_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('cartao',
    sa.Column('conta_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=32), nullable=True),
    sa.Column('brand', sa.String(length=32), nullable=True),
    sa.Column('brand_additional_info', sa.String(length=255), nullable=True),
    sa.Column('balance_close_date', sa.Date(), nullable=True),
    sa.Column('balance_due_date', sa.Date(), nullable=True),
    sa.Column('credit_limit_centavos', sa.BigInteger(), nullable=True),
    sa.Column('available_credit_limit_centavos', sa.BigInteger(), nullable=True),
    sa.Column('balance_foreign_currency_centavos', sa.BigInteger(), nullable=True),
    sa.Column('minimum_payment_centavos', sa.BigInteger(), nullable=True),
    sa.Column('is_limit_flexible', sa.Boolean(), nullable=True),
    sa.Column('holder_type', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['conta_id'], ['conta.id'], name=op.f('fk_cartao_conta_id_conta'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conta_id', name=op.f('pk_cartao'))
    )
    op.create_table('conta_bancaria',
    sa.Column('conta_id', sa.Integer(), nullable=False),
    sa.Column('transfer_number', sa.String(length=64), nullable=True),
    sa.Column('closing_balance_centavos', sa.BigInteger(), nullable=True),
    sa.Column('automatically_invested_balance_centavos', sa.BigInteger(), nullable=True),
    sa.Column('overdraft_contracted_limit_centavos', sa.BigInteger(), nullable=True),
    sa.Column('overdraft_used_limit_centavos', sa.BigInteger(), nullable=True),
    sa.Column('unarranged_overdraft_amount_centavos', sa.BigInteger(), nullable=True),
    sa.Column('has_reserved_balance', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['conta_id'], ['conta.id'], name=op.f('fk_conta_bancaria_conta_id_conta'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conta_id', name=op.f('pk_conta_bancaria'))
    )
    op.create_table('investimento_transacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investimento_id', sa.Integer(), nullable=False),
    sa.Column('pluggy_id', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=8), nullable=False),
    sa.Column('movement_type', sa.String(length=8), nullable=False),
    sa.Column('amount_centavos', sa.BigInteger(), nullable=False),
    sa.Column('value_unitario', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('net_amount_centavos', sa.BigInteger(), nullable=True),
    sa.Column('expenses_centavos', sa.BigInteger(), nullable=True),
    sa.Column('trade_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('brokerage_number', sa.String(length=64), nullable=True),
    sa.CheckConstraint("movement_type IN ('CREDIT', 'DEBIT')", name=op.f('ck_investimento_transacao_movement_type')),
    sa.CheckConstraint("type IN ('BUY', 'SELL')", name=op.f('ck_investimento_transacao_type')),
    sa.ForeignKeyConstraint(['investimento_id'], ['investimento.id'], name=op.f('fk_investimento_transacao_investimento_id_investimento'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investimento_transacao')),
    sa.UniqueConstraint('pluggy_id', name=op.f('uq_investimento_transacao_pluggy_id'))
    )
    with op.batch_alter_table('investimento_transacao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investimento_transacao_investimento_id'), ['investimento_id'], unique=False)

    op.create_table('conta_saldo_reservado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conta_bancaria_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('identificacao', sa.String(length=255), nullable=True),
    sa.Column('valor_centavos', sa.BigInteger(), nullable=True),
    sa.Column('rem_indexer', sa.String(length=32), nullable=True),
    sa.Column('rem_rate_type', sa.String(length=32), nullable=True),
    sa.Column('rem_pre_fixed_rate', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('rem_periodicity', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['conta_bancaria_id'], ['conta_bancaria.conta_id'], name=op.f('fk_conta_saldo_reservado_conta_bancaria_id_conta_bancaria'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conta_saldo_reservado'))
    )
    with op.batch_alter_table('conta_saldo_reservado', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conta_saldo_reservado_conta_bancaria_id'), ['conta_bancaria_id'], unique=False)

    op.create_table('fatura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cartao_id', sa.Integer(), nullable=False),
    sa.Column('pluggy_bill_id', sa.String(length=64), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_amount_centavos', sa.BigInteger(), nullable=False),
    sa.Column('total_amount_currency_code', sa.String(length=3), nullable=True),
    sa.Column('minimum_payment_centavos', sa.BigInteger(), nullable=True),
    sa.Column('allows_installments', sa.Boolean(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cartao_id'], ['cartao.conta_id'], name=op.f('fk_fatura_cartao_id_cartao'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_fatura_usuario_id_usuario'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fatura')),
    sa.UniqueConstraint('pluggy_bill_id', name=op.f('uq_fatura_pluggy_bill_id'))
    )
    with op.batch_alter_table('fatura', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fatura_cartao_id'), ['cartao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fatura_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('fatura_encargo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fatura_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=64), nullable=False),
    sa.Column('valor_centavos', sa.BigInteger(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('additional_info', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['fatura_id'], ['fatura.id'], name=op.f('fk_fatura_encargo_fatura_id_fatura'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fatura_encargo'))
    )
    with op.batch_alter_table('fatura_encargo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fatura_encargo_fatura_id'), ['fatura_id'], unique=False)

    op.create_table('fatura_pagamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fatura_id', sa.Integer(), nullable=False),
    sa.Column('valor_centavos', sa.BigInteger(), nullable=True),
    sa.Column('data', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fatura_id'], ['fatura.id'], name=op.f('fk_fatura_pagamento_fatura_id_fatura'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fatura_pagamento'))
    )
    with op.batch_alter_table('fatura_pagamento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fatura_pagamento_fatura_id'), ['fatura_id'], unique=False)

    op.create_table('transacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=False),
    sa.Column('pluggy_transaction_id', sa.String(length=64), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_raw', sa.Text(), nullable=True),
    sa.Column('amount_centavos', sa.BigInteger(), nullable=False),
    sa.Column('amount_in_account_currency_centavos', sa.BigInteger(), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('type', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('balance_centavos', sa.BigInteger(), nullable=True),
    sa.Column('categoria_pluggy_id', sa.String(length=16), nullable=True),
    sa.Column('categoria_override_id', sa.String(length=16), nullable=True),
    sa.Column('categoria_ajustada_usuario', sa.Boolean(), nullable=False),
    sa.Column('merchant_cnpj', sa.String(length=20), nullable=True),
    sa.Column('merchant_cnae', sa.String(length=20), nullable=True),
    sa.Column('merchant_nome', sa.String(length=255), nullable=True),
    sa.Column('merchant_categoria', sa.String(length=255), nullable=True),
    sa.Column('operation_type', sa.String(length=64), nullable=True),
    sa.Column('provider_code', sa.String(length=64), nullable=True),
    sa.Column('provider_id', sa.String(length=64), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('bill_id', sa.Integer(), nullable=True),
    sa.Column('installment_number', sa.Integer(), nullable=True),
    sa.Column('total_installments', sa.Integer(), nullable=True),
    sa.Column('total_amount_centavos', sa.BigInteger(), nullable=True),
    sa.Column('payee_mcc', sa.Integer(), nullable=True),
    sa.Column('eh_transferencia', sa.Boolean(), nullable=False),
    sa.Column('revisada', sa.Boolean(), nullable=False),
    sa.Column('contraparte_id', sa.Integer(), nullable=True),
    sa.Column('transferencia_origem', sa.String(length=8), nullable=True),
    sa.Column('pluggy_criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pluggy_atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('POSTED', 'PENDING')", name=op.f('ck_transacao_status')),
    sa.CheckConstraint("transferencia_origem IN ('auto', 'manual')", name=op.f('ck_transacao_transferencia_origem')),
    sa.CheckConstraint("type IN ('DEBIT', 'CREDIT')", name=op.f('ck_transacao_type')),
    sa.ForeignKeyConstraint(['bill_id'], ['fatura.id'], name=op.f('fk_transacao_bill_id_fatura'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['categoria_override_id'], ['categoria.pluggy_id'], name=op.f('fk_transacao_categoria_override_id_categoria'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['categoria_pluggy_id'], ['categoria.pluggy_id'], name=op.f('fk_transacao_categoria_pluggy_id_categoria'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conta_id'], ['conta.id'], name=op.f('fk_transacao_conta_id_conta'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contraparte_id'], ['transacao.id'], name=op.f('fk_transacao_contraparte_id_transacao'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_transacao_usuario_id_usuario'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transacao')),
    sa.UniqueConstraint('pluggy_transaction_id', name=op.f('uq_transacao_pluggy_transaction_id'))
    )
    with op.batch_alter_table('transacao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transacao_bill_id'), ['bill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transacao_categoria_override_id'), ['categoria_override_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transacao_categoria_pluggy_id'), ['categoria_pluggy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transacao_conta_id'), ['conta_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transacao_contraparte_id'), ['contraparte_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transacao_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('transacao_pagamento',
    sa.Column('transacao_id', sa.Integer(), nullable=False),
    sa.Column('metodo', sa.String(length=16), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('reference_number', sa.String(length=64), nullable=True),
    sa.Column('receiver_reference_id', sa.String(length=64), nullable=True),
    sa.Column('payer_nome', sa.String(length=255), nullable=True),
    sa.Column('payer_conta', sa.String(length=64), nullable=True),
    sa.Column('payer_agencia', sa.String(length=32), nullable=True),
    sa.Column('payer_doc_tipo', sa.String(length=8), nullable=True),
    sa.Column('payer_doc_valor', sa.String(length=32), nullable=True),
    sa.Column('receiver_nome', sa.String(length=255), nullable=True),
    sa.Column('receiver_conta', sa.String(length=64), nullable=True),
    sa.Column('receiver_agencia', sa.String(length=32), nullable=True),
    sa.Column('receiver_doc_tipo', sa.String(length=8), nullable=True),
    sa.Column('receiver_doc_valor', sa.String(length=32), nullable=True),
    sa.Column('boleto_base_amount_centavos', sa.BigInteger(), nullable=True),
    sa.Column('boleto_interest_centavos', sa.BigInteger(), nullable=True),
    sa.Column('boleto_discount_centavos', sa.BigInteger(), nullable=True),
    sa.Column('boleto_penalty_centavos', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['transacao_id'], ['transacao.id'], name=op.f('fk_transacao_pagamento_transacao_id_transacao'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('transacao_id', name=op.f('pk_transacao_pagamento'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transacao_pagamento')
    with op.batch_alter_table('transacao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transacao_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_transacao_contraparte_id'))
        batch_op.drop_index(batch_op.f('ix_transacao_conta_id'))
        batch_op.drop_index(batch_op.f('ix_transacao_categoria_pluggy_id'))
        batch_op.drop_index(batch_op.f('ix_transacao_categoria_override_id'))
        batch_op.drop_index(batch_op.f('ix_transacao_bill_id'))

    op.drop_table('transacao')
    with op.batch_alter_table('fatura_pagamento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fatura_pagamento_fatura_id'))

    op.drop_table('fatura_pagamento')
    with op.batch_alter_table('fatura_encargo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fatura_encargo_fatura_id'))

    op.drop_table('fatura_encargo')
    with op.batch_alter_table('fatura', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fatura_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_fatura_cartao_id'))

    op.drop_table('fatura')
    with op.batch_alter_table('conta_saldo_reservado', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conta_saldo_reservado_conta_bancaria_id'))

    op.drop_table('conta_saldo_reservado')
    with op.batch_alter_table('investimento_transacao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investimento_transacao_investimento_id'))

    op.drop_table('investimento_transacao')
    op.drop_table('conta_bancaria')
    op.drop_table('cartao')
    with op.batch_alter_table('assinatura', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assinatura_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_assinatura_conta_id'))
        batch_op.drop_index(batch_op.f('ix_assinatura_categoria_id'))

    op.drop_table('assinatura')
    with op.batch_alter_table('investimento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investimento_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_investimento_objetivo_id'))
        batch_op.drop_index(batch_op.f('ix_investimento_item_id'))

    op.drop_table('investimento')
    with op.batch_alter_table('conta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conta_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_conta_objetivo_id'))
        batch_op.drop_index(batch_op.f('ix_conta_item_id'))
        batch_op.drop_index(batch_op.f('ix_conta_instituicao_id'))

    op.drop_table('conta')
    with op.batch_alter_table('orcamento_mensal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orcamento_mensal_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_orcamento_mensal_orcamento_id'))
        batch_op.drop_index(batch_op.f('ix_orcamento_mensal_categoria_id'))

    op.drop_table('orcamento_mensal')
    with op.batch_alter_table('item_pluggy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_pluggy_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_item_pluggy_credencial_id'))

    op.drop_table('item_pluggy')
    with op.batch_alter_table('sessao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessao_usuario_id'))

    op.drop_table('sessao')
    with op.batch_alter_table('orcamento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orcamento_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_orcamento_categoria_id'))

    op.drop_table('orcamento')
    with op.batch_alter_table('objetivo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_objetivo_usuario_id'))

    op.drop_table('objetivo')
    with op.batch_alter_table('instituicao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instituicao_usuario_id'))

    op.drop_table('instituicao')
    with op.batch_alter_table('fonte_de_renda', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fonte_de_renda_usuario_id'))

    op.drop_table('fonte_de_renda')
    with op.batch_alter_table('divisao_despesa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_divisao_despesa_outro_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_divisao_despesa_criado_por_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_divisao_despesa_categoria_id'))

    op.drop_table('divisao_despesa')
    with op.batch_alter_table('credencial_pluggy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credencial_pluggy_usuario_id'))

    op.drop_table('credencial_pluggy')
    with op.batch_alter_table('config_telegram', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_config_telegram_usuario_id'))

    op.drop_table('config_telegram')
    op.drop_table('usuario')
    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categoria_parent_id'))

    op.drop_table('categoria')
    # ### end Alembic commands ###
