"""fii_fundamento e brapi_token

Revision ID: c1084e6ceddd
Revises: b2d9f4a71c60
Create Date: 2026-07-27 08:48:19.763114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1084e6ceddd'
down_revision: Union[str, Sequence[str], None] = 'b2d9f4a71c60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fii_fundamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isin', sa.String(length=20), nullable=False),
    sa.Column('cnpj', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('administrador_nome', sa.String(length=255), nullable=True),
    sa.Column('administrador_cnpj', sa.String(length=20), nullable=True),
    sa.Column('data_funcionamento', sa.Date(), nullable=True),
    sa.Column('segmento', sa.String(length=64), nullable=True),
    sa.Column('mandato', sa.String(length=64), nullable=True),
    sa.Column('tipo_gestao', sa.String(length=32), nullable=True),
    sa.Column('tipo', sa.String(length=16), nullable=True),
    sa.Column('patrimonio_liquido_centavos', sa.BigInteger(), nullable=True),
    sa.Column('num_cotistas', sa.Integer(), nullable=True),
    sa.Column('valor_patrimonial_cota_centavos', sa.BigInteger(), nullable=True),
    sa.Column('dividend_yield_12m_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('vacancia_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('inadimplencia_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('data_referencia', sa.Date(), nullable=False),
    sa.Column('data_referencia_trimestral', sa.Date(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fii_fundamento'))
    )
    with op.batch_alter_table('fii_fundamento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fii_fundamento_isin'), ['isin'], unique=True)

    op.create_table('fii_fundamento_alocacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fundamento_id', sa.Integer(), nullable=False),
    sa.Column('classe', sa.String(length=64), nullable=False),
    sa.Column('valor_centavos', sa.BigInteger(), nullable=False),
    sa.Column('pct', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['fundamento_id'], ['fii_fundamento.id'], name=op.f('fk_fii_fundamento_alocacao_fundamento_id_fii_fundamento'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fii_fundamento_alocacao'))
    )
    with op.batch_alter_table('fii_fundamento_alocacao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fii_fundamento_alocacao_fundamento_id'), ['fundamento_id'], unique=False)

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brapi_token_cifrado', sa.Text(), nullable=True))

    # Nota: o autogenerate re-detecta VARCHAR(8)→String(16) nas FKs categoria_id/pluggy_id — ruído
    # conhecido (compare_type + PK String(16) da categoria), removido à mão. Não é mudança de schema.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('brapi_token_cifrado')

    with op.batch_alter_table('fii_fundamento_alocacao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fii_fundamento_alocacao_fundamento_id'))

    op.drop_table('fii_fundamento_alocacao')
    with op.batch_alter_table('fii_fundamento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fii_fundamento_isin'))

    op.drop_table('fii_fundamento')
    # ### end Alembic commands ###
